name: HCU Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with CMake
        run: |
          cmake -B build -S src/HCU -DCMAKE_CXX_FLAGS="-Wall -Wextra"
          cmake --build build